services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/JasonnVo/U-Link
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ulink-db
          property: connectionString

  - type: web
    name: frontend
    env: docker
    repo: https://github.com/JasonnVo/U-Link
    plan: free
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
